Pre fill ticket services
ubclaunchpad/labby pull request #68
Opened 2023-02-01 07:08 UTC by jjessieshang

Pre-filling tickets with cost estimates of services.

2023-02-01 20:33 UTC, Harin329 requested changes
Looks good! Just some small linting changes, to try to keep the code base cleaner moving forward

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/components/CostEstimate/index.js
> +        { console.log(costEstimateBillablesMap)}
Can we remove this logging here :)

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/redux/reducers/costEstimateReducer.js
> +import { SET_COST} from "../actions/costActions";
lint nit: space here

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/redux/reducers/ticketReducer.js
> +  switch (action.type) {
lint nit: space

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/redux/saga/surveySaga.js
> +    payload.formResponses.map((response) => {
space

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/screens/request-form/request-form.js
> +import { LOAD_COST} from "../../redux/actions/costActions";
space

2023-02-01 20:33 UTC, Harin329 commented on frontend/src/redux/saga/surveySaga.js
> +  yield all(
Nice! Yield all sagas can get confusing, this looks good

2023-02-02 05:30 UTC, jjessieshang commented
sounds good, will be more careful with the styling in the future :)

2023-02-02 06:55 UTC, Harin329 approved these changes

2023-02-02 06:55 UTC, merged